before_install:
    - ROOT=$(pwd)
    - cd /tmp
    - curl -O  https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.11.6.tar.gz
    - tar -zxvf virtualenv-1.11.6.tar.gz
    - cd virtualenv-1.11.6
    - sudo python setup.py install
    - cd /usr/local
    - sudo virtualenv lb
    - cd /usr/local/lb
    - sudo mkdir src
    - cd src
    - sudo cp -R $ROOT LBConverter



script:
    - echo Teste python
    - cd /usr/local/lb/src/LBConverter
    - sudo /usr/local/lb/bin/python setup.py install

