language: python
python:
  - "3.4"
install:
  - apt-get install python3-desudo: required

language: ruby

services:
  - docker

before_install:
- docker run -it ubuntu /bin/bash
script:
- bundle exec rake testv
script:
  - cd neolight
after_success: coveralls

